### ISSUE TITLE
Forgotten pod trunk push?

### ISSUE THREAD

**Issue by fvolchyok** [AckeeCZ/Reqres#27] opened 2020-05-04 08:54 UTC
Event though version 3.1.1 seems like ready-to-use I can't download it from cocoapods main repo, probably due to forgotten `pod trunk push`. From there I can download only 3.1.0 (https://cocoapods.org/pods/Reqres)

**Comment by olejnjak** [comment] 2020-05-04 09:11
Hi @fvolchyok, 

thanks for the issue, we'll look into it in a moment, but for now I'll close this issue as it is a duplicate of #26.

**Closed as completed by olejnjak** 2020-05-04 09:11 UTC
